### ISSUE TITLE
README missing info about how to import decorator

### ISSUE THREAD

**Issue by km-pg** [django-silk/silk#180]
The README doesn't say where to import the silk_profile decorator from. Not sure where to find it.

**Comment by avelis** [comment]
@km-pg For quick resolution here is a comment from another closed ticket on how to import the decorator.
https://github.com/django-silk/silk/issues/172#issuecomment-289226063

Since this is the second ticket come in with this I will make sure the README gets a note on the decorators import location.

**Comment by avelis** [comment]
@km-pg README.md has updated example code with imports highlighting the location of the profiler.

**Comment by km-pg** [comment]
Cool, thanks!
