### ISSUE TITLE
running python manage.py silk_clear_request_log it finishes with 'killed'

### ISSUE THREAD

**Issue by ricardodanieltapia** [django-silk/silk#73]
Hello guys,

I ran a jmeter script to perform load, after that I tried to clean the log and I got the message:
deleting Profile 0 objects
deleting SQLQuery 201290 objects
killed

The thing is the logs were not deleted right?
could you provide advise please?

Best regards

**Comment by mtford90** [comment]
Hey @ricardodanieltapia sorry for the delay in getting to this. Here is what happens when I execute this command:

```
$ ./manage.py silk_clear_request_log
deleting Profile 4 objects
deleting SQLQuery 2 objects
deleting Response 2 objects
deleting Request 2 objects
```

This successfully clears the database for me. Where is `killed` coming from in your output? I'm not familiar with jmeter but it looks like the script is being killed prior to completion?

**Comment by avelis** [comment]
@ricardodanieltapia This would appear that some other parameters are missing in order to fulling understand what is happening with this issue? Could it be possible that another process killed the management command from completion?

**Comment by javaguirre** [comment]
Could It be out of memory? You can check with `free` if your database is out of memory, the process will be killed if that's the case.

**Comment by avelis** [comment]
Closing this issue. If there is more information about why management command is killed I can possibly investigate.
